name: Board
main: ru.boomearo.board.Board
version: ${project.version}
author: BoomEaro
description: advanced board
api-version: 1.13
commands:
  board:
    usage: /board
    description: advanced board