name: Board
main: ru.boomearo.board.Board
version: 0.5.1
author: BoomEaro
description: advanced board
api-version: 1.16
depend: [ServerUtils]
commands:
  board:
    usage: /board
    description: advanced board