name: Board
main: ru.boomearo.board.Board
version: '${version}'
author: BoomEaro
description: advanced board
api-version: 1.13
softdepend: [ PlaceholderAPI ]
commands:
  board:
    usage: /board
    description: advanced board