name: Board
main: ru.boomearo.board.Board
version: 0.5.1
author: BoomEaro
description: advanced board
softdepend: [MyPet, Cities, Nations, AdvEco, Quests]
commands:
  board:
    usage: /board
    description: advanced board